services:
  base:
    build: .
    volumes:
      - .:/code
    working_dir: /code
    tty: true
  check:
    extends: base
    command: bash --login -c '
      cmake --preset clang && cmake --build build_clang -t check -j8'
  check_full:
    extends: base
    command: bash --login -c '
      cmake --preset clang && cmake --build build_clang -t check_full -j8'
  iwyu:
    extends: base
    command: bash --login -c '
      cmake --preset clang && cmake --build build_clang -t iwyu -j8'
  fixme:
    extends: base
    command: bash --login -c '
      cmake -P cmake/fixme.cmake'
  clangd:
    extends: base
    ports:
      - "50000:50000"
    command: socat tcp-listen:50000,reuseaddr exec:'clangd --path-mappings="$PWD=/code/"'
  doc:
    extends: base
    command: bash --login -c '
      cmake -B build &&
      cmake --build build -t doc'
  shell:
    extends: base
    command: bash
