services:
  base:
    build: .
    volumes:
      - .:/home/paulin/Unpadded
    working_dir: /home/paulin/Unpadded
    tty: true
  check:
    extends: base
    command: bash --login -c '
      cmake --preset user && cmake --build build_clang -t check -j8'
  check_full:
    extends: base
    command: bash --login -c '
      cmake --preset user && cmake --build build_clang -t check_full -j8'
  examples:
    extends: base
    command: bash --login -c '
      cmake --preset user && cmake --build build_clang -t upd_examples -j8'
  iwyu:
    extends: base
    command: bash --login -c '
      cmake --preset user && cmake --build build_clang -t iwyu -j8'
  iwyu_k:
    extends: base
    command: bash --login -c '
      cmake --preset user && cmake --build build_clang -t iwyu -j8 -- -k'
  quick_iwyu:
    extends: base
    command: bash --login -c '
      cmake --preset user && cmake --build build_clang -t quick_iwyu -j1'
  fixme:
    extends: base
    command: bash --login -c '
      cmake -P cmake/fixme.cmake'
  clangd:
    extends: base
    ports:
      - "50000:50000"
    command: socat tcp-listen:50000,reuseaddr exec:'clangd --path-mappings="$PWD=/code/"'
  doc:
    extends: base
    command: bash --login -c '
      cmake -B build &&
      cmake --build build -t doc'
  shell:
    extends: base
    command: bash
  debug_unitary:
    extends: base
    command: gdb build_clang/test/upd_unitary
  report_build_time:
    extends: base
    command: |
      bash -c '
        set -euo pipefail

        ClangBuildAnalyzer --all build_clang capture.bin

        echo "| File | Build Duration |"
        echo "| --- | --- |"

        ClangBuildAnalyzer --analyze capture.bin \
        | awk "/Files that took longest to parse/ {
            flag=1
            next
          }
          flag && /^$/ {exit}
          flag { gsub(/ms/, \"\") }" 
        | while read -r duration filepath; do
          printf "| %s | %s |\n" \
            "$(basename "$filepath")"
            "$(date --utc --date="@$duration" +"%Mmin %Ss")"
        done
      '
